<?php
$this->headScript()->appendFile('/js/admin/member/edit.js');
?>
<?php if ($this->storedPresentsFor) : ?>
<?php foreach ($this->storedPresentsFor as $key => $value) : ?>
    <input type="text" name="presentsFor[<?php echo $key ?>]" class="presentsFor" value="<?php echo $value ?>"/>
<?php endforeach; ?>
<?php endif; ?>

<?php if ($this->storedCoordinatesFor) : ?>
<?php foreach (array_values($this->storedCoordinatesFor) as $key => $value) : ?>
    <input type="text" name="coordinatesFor[<?php echo $key ?>]" class="coordinatesFor" value="<?php echo $value ?>"/>
<?php endforeach; ?>
<?php endif; ?>

<?php if ($this->storedFacilitatesFor) : ?>
<?php foreach ($this->storedFacilitatesFor as $key => $value) : ?>
    <input type="text" name="facilitatesFor[<?php echo $key ?>]" class="facilitatesFor" value="<?php echo $value ?>"/>
<?php endforeach; ?>
<?php endif; ?>

<?php if ($this->member->getAssociatedUserId()): ?>
<div class="alert alert-info">
    <strong>Note:</strong> This member can access the system with the username: "<?php echo $this->member->getAssociatedUserId(); ?>".
    This username and password can be updated below.
</div>
<?php endif; ?>
<?php echo $this->form; ?>