<?php
$columns = array('Role', 'Status' ,'Last Name, First Name', 'City', 'State');
?>
<table class="table table-striped table-bordered">
	<thead>
		<tr>
		<?php foreach ($columns as $title){
			echo "<th>$title</th>";
			}?>
			<th style="text-align:right;">Actions</th>
		</tr>
	</thead>
	<tbody>
	<?php	foreach ($this->members as $id => $member) {
	    ?>
		<tr <?php echo $member['deceased'] ? 'class="muted"' : ""; ?>>
		<td>
		    <span class="label <?php echo $member['roleClass']; ?>"><?php echo $member['role']; ?></span>
		</td>
		<td <?php echo $member['deceased'] ? 'class="deceased"' : ""; ?>>
			<?php echo $member['status']; ?>
		</td>
		<td <?php echo $member['deceased'] ? 'class="deceased"' : ""; ?>>
		    <?php echo $member['lastName'].', '. $member['firstName']; ?>
		</td>
		<td <?php echo $member['deceased'] ? 'class="deceased"' : ""; ?>>
		    <?php echo $member['city']; ?>
		</td>
		<td <?php echo $member['deceased'] ? 'class="deceased"' : ""; ?>>
		    <?php echo $member['state']; ?>
		</td>
			<td style="text-align:right;">
			<a class="btn btn-mini" href="/admin/member/view?id=<?php echo $id; ?>"><i class="icon-info-sign"></i> Details</a>
			</td>
		<?php }?>	
		</tr>
	</tbody>
</table>