<script type="text/javascript">
    $(document).ready(function() {
        $('.confirm-delete').bind('click', function(){
            var id = $(this).data('id'),
                name = $(this).data('fullname');
            $('#memberDeleteModal').data({'id': id, 'fullname': name}).modal('show');
        })
        $('#memberDeleteModal').bind('show', function() {
            var id = $(this).data('id'),
                name = $(this).data('fullname'),
                removeBtn = $(this).find('.btn-danger'),
                href = removeBtn.attr('href');
                content = $('.modal-body p').html();
                $('.confirm-message').html(content.replace(/~member~/, name));
                removeBtn.attr('href', href.replace(/\?id=.*/, '?id=' + id));
        }).modal({
            backdrop: true,
            show: false
        });
    });
</script>



<div class="accordion" id="accordion2">
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
        <em><i class="icon-filter"></i> Filter List...</em>
      </a>
    </div>
    <div id="collapseOne" class="accordion-body collapse">
      <div class="accordion-inner">
        <?php echo $this->form ?>
      </div>
    </div>
  </div>
</div>
<?php
$columns = array('Role', 'Status' ,'Last Name, First Name', 'Email', 'City', 'State');
?>
<p>
    <?php if ($this->can_view_training): ?>
    <a class="btn btn-info" href="/admin/member/training">View Training Completion</a>
    <?php endif; ?>

    <a class="btn btn-info" href="/admin/member/excel">Download</a>
</p>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
        <?php foreach ($columns as $title): ?>
            <th><?= $title ?></th>
        <?php endforeach; ?>
            <th style="text-align:right;">Actions</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->members as $id => $member): ?>
        <tr <?php echo $member['deceased'] ? 'class="muted"' : ""; ?>>
            <td>
                <span class="label <?php echo $member['roleClass']; ?>"><?php echo $member['role']; ?></span>
                <?php if($member['hasNotes']) { echo '<i class="icon-paper-clip"/>'; } ?>
            </td>
            <td <?php echo $member['deceased'] ? 'class="deceased"' : ""; ?>>
                <?php echo $member['status']; ?>
            </td>
            <td <?php echo $member['deceased'] ? 'class="deceased"' : ""; ?>>
                <?php echo $member['lastName'].', '. $member['firstName']; ?>
            </td>
            <td <?php echo $member['deceased'] ? 'class="deceased"' : ""; ?>>
                <?php echo sprintf('<a href="mailto:%s">%s</a>', $member['email'], $member['email']) ?>
            </td>
            <td <?php echo $member['deceased'] ? 'class="deceased"' : ""; ?>>
                <?php echo $member['city']; ?>
            </td>
            <td <?php echo $member['deceased'] ? 'class="deceased"' : ""; ?>>
                <?php echo $member['state']; ?>
            </td>
            <td style="text-align:right;">
                <div class="btn-group">
                <?php if ($this->can_view): ?>
                    <a class="btn btn-mini" href="/admin/member/view?id=<?php echo $id; ?>"><i class="icon-info-sign"></i> Details</a>
                <?php endif; ?>
                <?php if ($this->can_edit): ?>
                    <a class="btn btn-mini btn-primary" href="/admin/member/edit?id=<?php echo $id ?>"><i class="icon-edit"></i></a>
                <?php endif; ?>
                <?php if ($this->can_delete && $member['canBeDeleted']): ?>
                    <a class="btn btn-mini btn-danger confirm-delete" data-fullname="<?php echo $member['firstName'] .' ' . $member['lastName']; ?>" data-id="<?php echo $id; ?>" href="#"><i class="icon-trash"></i></a>
                <?php elseif ($this->can_delete): ?>
                    <a class="btn btn-mini btn-danger disabled" href="#"><i class="icon-trash"></i></a>
                <?php endif; ?>
                </div>
            </td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>

<div id="memberDeleteModal" class="modal hide fade">
    <div class="modal-header">
      <a href="#" class="close">&times;</a>
      <h3>Delete Member</h3>
    </div>
    <div class="modal-body">
      <p class="confirm-message">You are about to delete the member ~member~, this procedure is irreversible.</p>
      <p>Are you sure you want to do this?</p>
    </div>
    <div class="modal-footer">
      <a href="/admin/member/delete?id=" class="btn btn-danger">Yes</a>
      <a href="javascript:$('#memberDeleteModal').modal('hide')" class="btn btn-secondary">No</a>
    </div>
</div>