<?php
$this->headScript()->appendFile('/js/admin/member/edit.js');
?>

<div class="page-header">
    <h1>New Member
        <small>Enter new member details here.</small>
    </h1>
</div>

<?php if ($this->storedPresentsFor) : ?>
<?php foreach ($this->storedPresentsFor as $key => $value) : ?>
    <input type="text" name="presentsFor[<?php echo $key ?>]" class="presentsFor" value="<?php echo $value ?>"/>
<?php endforeach; ?>
<?php endif; ?>

<?php if ($this->storedCoordinatesFor) : ?>
<?php foreach ($this->storedCoordinatesFor as $key => $value) : ?>
    <input type="text" name="coordinatesFor[<?php echo $key ?>]" class="coordinatesFor" value="<?php echo $value ?>"/>
<?php endforeach; ?>
<?php endif; ?>

<?php if ($this->storedFacilitatesFor) : ?>
<?php foreach ($this->storedFacilitatesFor as $key => $value) : ?>
    <input type="text" name="facilitatesFor[<?php echo $key ?>]" class="facilitatesFor" value="<?php echo $value ?>"/>
<?php endforeach; ?>
<?php endif; ?>

<?php echo $this->form; ?>
