<dl class="dl-horizontal">
  <dt>Type:</dt>
  <dd><?php echo $this->member->getType() ? $this->member->getType() : '-'; ?></dd>
  <dt>Status:</dt>
  <dd><?php echo $this->member->getStatus() ? $this->member->getStatus() : '-'; ?></dd>
  <dt>Date Trained:</dt>
  <dd><?php echo $this->member->getDateTrained() ? $this->member->getDateTrained() : '-'; ?></dd>
  <dt>Notes:</dt>
  <dd>
  <?php echo $this->member->getNotes() ? $this->member->getNotes() : '-'; ?>
  </dd>
  <dt>Email:</dt>
  <dd><?php echo $this->member->getEmail() ? '<a href="mailto:'.$this->member->getEmail().'">'.$this->member->getEmail().'</a>' : '-'; ?></dd>
  
  <?php 
    $phoneNumbers = $this->member->getPhoneNumbers();
    if (! empty($phoneNumbers)):
      echo "<br>";
      foreach ($phoneNumbers as $phoneNumber):
  ?>
  <dt><?php echo ucfirst($phoneNumber['type']); ?> <i class="icon-phone"></i></dt>
  <dd><?php echo preg_replace('/([0-9]{3})([0-9]{3})([0-9]{4})/', '$1-$2-$3', $phoneNumber['number']); ?></dd>
  
  <?php 
    endforeach;
    endif;
  ?>

  <br>
  <dt>Date of Diagnosis:</dt>
  <dd><?php echo $this->member->getDiagnosisDate() ? $this->member->getDiagnosisDate() : '-'; ?></dd>
  <dt>Diagnosis Stage:</dt>
  <dd><?php echo $this->member->getDiagnosisStage() ? $this->member->getDiagnosisStage() : '-'; ?></dd>

  <br>
  <dt>Address:</dt>
  <dd><address>
  <?php echo $this->member->getAddressLineOne() ? $this->member->getAddressLineOne() : '-' ?><br>
    <?php echo $this->member->getAddressLineTwo() ? $this->member->getAddressLineTwo().'<br>' : '' ?>
  <?php echo $this->member->getAddressCity() ? $this->member->getAddressCity().',':''?> <?php echo $this->member->getAddressState() ?> <?php echo $this->member->getAddressZip() ?><br>
</address></dd>

<?php if(! $this->member->getPresentsForAreas()==array() ):?>
    <dt>Presents For:</dt>
    <dd>
    <?php foreach($this->member->getPresentsForAreas() as $area):?>
        <span class="label"><?php echo $area; ?></span>
    <?php endforeach; ?>
    </dd>
<?php endif;?>

<?php if(! $this->member->getFacilitatesForAreas()==array() ):?>
    <dt>Facilitates For:</dt>
    <dd>
    <?php foreach($this->member->getFacilitatesForAreas() as $area):?>
        <span class="label label-info"><?php echo $area; ?></span>
    <?php endforeach; ?>
    </dd>
<?php endif;?>

<?php if(! $this->member->getCoordinatesForRegions()==array() ):?>
    <dt>Coordinates For:</dt>
    <dd>
    <?php foreach($this->member->getCoordinatesForRegions() as $region):?>
        <span class="label label-warning"><?php echo $region; ?></span>
    <?php endforeach; ?>
    </dd>
<?php endif;?>

</dl>
<br>

<?php if($this->user):?>
<div class="alert alert-info">
<h4>System User Details</h4>
<small class="muted">This member has an account to access this system, thier details are below:</small>
<dl class="dl-horizontal">
<dt>System Role:</dt>
  <dd><?php echo $this->user->getRole() ? $this->user->getRole() : '-'; ?></dd>
  <dt>Username:</dt>
  <dd><?php echo $this->user->getId() ? $this->user->getId() : '-'; ?></dd>
  <dt>Email Address:</dt>
  <dd><?php echo $this->user->getEmail() ? '<a href="mailto:'.$this->user->getEmail().'">'.$this->user->getEmail().'</a>' : '-'; ?></dd>
  </dl>
</div>
<?php endif;?>
<div class="well">
<div class="btn-toolbar">
<a class="btn" href="/admin/member">Go Back</a>
</div></div>