<script type="text/javascript">
  $(document).ready(function() {
    $('.confirm-delete').bind('click', function(){
      var id = $(this).data('id'),
        name = $(this).data('fullname');
      $('#memberDeleteModal').data({'id': id, 'fullname': name}).modal('show');
    })
    $('#memberDeleteModal').bind('show', function() {
      var id = $(this).data('id'),
        name = $(this).data('fullname'),
        removeBtn = $(this).find('.btn-danger'),
        href = removeBtn.attr('href');
        content = $('.modal-body p').html();
        $('.confirm-message').html(content.replace(/~member~/, name));
        removeBtn.attr('href', href.replace(/\?id=.*/, '?id=' + id));
    }).modal({ 
      backdrop: true,
      show: false
    });
  });
</script>
<dl class="dl-horizontal">
  <dt>Type:</dt>
  <dd><?php echo $this->member->getType() ? $this->member->getType() : '-'; ?></dd>
  <dt>Status:</dt>
  <dd><?php echo $this->member->getStatus() ? $this->member->getStatus() : '-'; ?></dd>
  <dt>Date Trained:</dt>
  <dd><?php echo $this->member->getDateTrained() ? $this->member->getDateTrained() : '-'; ?></dd>
  <dt>Email:</dt>
  <dd><?php echo $this->member->getEmail() ? '<a href="mailto:'.$this->member->getEmail().'">'.$this->member->getEmail().'</a>' : '-'; ?></dd>
  
  <?php 
    $phoneNumbers = $this->member->getPhoneNumbers();
    if (! empty($phoneNumbers)):
      echo "<br>";
      foreach ($phoneNumbers as $phoneNumber):
  ?>
  <dt><?php echo ucfirst($phoneNumber['type']); ?> <i class="icon-phone"></i></dt>
  <dd><?php echo preg_replace('/([0-9]{3})([0-9]{3})([0-9]{4})/', '$1-$2-$3', $phoneNumber['number']); ?></dd>
  
  <?php 
    endforeach;
    endif;
  ?>

  <br>
  <dt>Date of Diagnosis:</dt>
  <dd><?php echo $this->member->getDiagnosisDate() ? $this->member->getDiagnosisDate() : '-'; ?></dd>
  <dt>Diagnosis Stage:</dt>
  <dd><?php echo $this->member->getDiagnosisStage() ? $this->member->getDiagnosisStage() : '-'; ?></dd>

  <br>
  <dt>Address:</dt>
  <dd><address>
  <?php echo $this->member->getAddressLineOne() ? $this->member->getAddressLineOne() : '-' ?><br>
    <?php echo $this->member->getAddressLineTwo() ? $this->member->getAddressLineTwo().'<br>' : '' ?>
  <?php echo $this->member->getAddressCity() ? $this->member->getAddressCity().',':''?> <?php echo $this->member->getAddressState() ?> <?php echo $this->member->getAddressZip() ?><br>
</address></dd>

<?php if(! $this->member->getPresentsForAreas()==array() ):?>
    <dt>Presents For:</dt>
    <dd>
    <?php foreach($this->member->getPresentsForAreas() as $area):?>
        <span class="label"><?php echo $area; ?></span>
    <?php endforeach; ?>
    </dd>
<?php endif;?>

<?php if(! $this->member->getFacilitatesForAreas()==array() ):?>
    <dt>Facilitates For:</dt>
    <dd>
    <?php foreach($this->member->getFacilitatesForAreas() as $area):?>
        <span class="label label-info"><?php echo $area; ?></span>
    <?php endforeach; ?>
    </dd>
<?php endif;?>

<?php if(! $this->member->getCoordinatesForRegions()==array() ):?>
    <dt>Coordinates For:</dt>
    <dd>
    <?php foreach($this->member->getCoordinatesForRegions() as $region):?>
        <span class="label label-warning"><?php echo $region; ?></span>
    <?php endforeach; ?>
    </dd>
<?php endif;?>

</dl>
<br>

<?php if($this->user):?>
<div class="alert alert-info">
<h4>System User Details</h4>
<small class="muted">This member has an account to access this system, their details are below:</small>
<dl class="dl-horizontal">
<dt>System Role:</dt>
  <dd><?php echo $this->user->getRole() ? $this->user->getRole() : '-'; ?></dd>
  <dt>Username:</dt>
  <dd><?php echo $this->user->getId() ? $this->user->getId() : '-'; ?></dd>
  <dt>Email Address:</dt>
  <dd><?php echo $this->user->getEmail() ? '<a href="mailto:'.$this->user->getEmail().'">'.$this->user->getEmail().'</a>' : '-'; ?></dd>
  </dl>
</div>
<?php endif;?>

<?php if($this->member->getNotes()): ?>
  <hr>
  <dl class="dl-horizontal">
  <dt>Notes:</dt>
  <dd>
  <?php echo $this->member->getNotes() ?>
  </dd>
  <br>
<?php endif; ?>

<div class="well">
<div class="btn-toolbar">
<div class="btn-group">
<a class="btn btn-primary" href="/admin/member/edit?id=<?php echo $this->member->getId() ?>"><i class="icon-edit"></i> Edit</a>
<?php if($this->member->canBeDeleted()): ?>
        <a class="btn btn-danger confirm-delete" data-fullname="<?php echo $this->member->getFirstName() .' ' . $this->member->getLastName() ?>" data-id="<?php echo $this->member->getId(); ?>" href="#"><i class="icon-trash"></i> Delete</a>
      <?php else: ?>
        <a id="delete-button" rel="tooltip" data-original-title="This member is linked with other items and can not be deleted." class="btn btn-danger disabled" href="#"><i class="icon-trash"></i> Delete</a> 
      <?php endif; ?>
</div>
      <a class="btn" href="/admin/member">Go Back</a>
</div>
</div>

<div id="memberDeleteModal" class="modal hide fade">
    <div class="modal-header">
      <a href="#" class="close">&times;</a>
      <h3>Delete Member</h3>
    </div>
    <div class="modal-body">
      <p class="confirm-message">You are about to delete the member ~member~, this procedure is irreversible.</p>
      <p>Are you sure you want to do this?</p>
    </div>
    <div class="modal-footer">
      <a href="/admin/member/delete?id=" class="btn btn-danger">Yes</a>
      <a href="javascript:$('#memberDeleteModal').modal('hide')" class="btn btn-secondary">No</a>
    </div>
</div>