<?php
$columns = array('id'=>'Area Id', 'city'=>'City', 'state'=>'State', 'regionObject'=>array('name'=>'Region'));
?>

<table class="table table-striped table-bordered">
	<thead>
		<tr>
		<?php foreach ($columns as $title){
		    
		    if(is_array($title)){
		    	$values = array_values($title);
			echo "<th>".$values[0]."</th>";
		    }else{
		        
			echo "<th>$title</th>";
		    }
			
			
			
			
			}?>
			<th style="text-align:right;">Actions</th>
		</tr>
	</thead>
	<tbody>
	<?php	foreach ($this->objects as $object) {?>
		<tr>
		<?php foreach ($columns as $get=>$title){
		    
		    $method = 'get' . ucfirst($get);
		    if(is_array($title)){
		    	$subObject = $object->$method();
		    	$subMethod = 'get'.ucFirst(key($title));
			echo "<td>{$subObject->$subMethod()}</td>";
		    }else{
			echo "<td>{$object->$method()}</td>";
		        
		    }
		        
		    
		    
			}?>
			<td style="text-align:right;">
			<a class="btn btn-small" href="#"><i class="icon-pencil"></i> Edit</a>
			<a class="btn btn-small btn-danger" href="#"><i class="icon-trash icon-white"></i></a>
			
			</td>
		<?php }?>	
		</tr>
	</tbody>
</table>