<script type="text/javascript">
$(document).ready(function() {
    $('input.regionFor').tagedit({
        autocompleteURL : "/search/area",
        checkNewEntriesCaseSensitive: true,
        allowEdit: false,
        allowAdd: true,
        addedPostfix: ''
    });
});
</script>

<div class="page-header">
    <h1>New Area
        <small>Enter new area details here.</small>
    </h1>
    <p>To create a new region, it must have a new area.</p>
</div>

<?php echo $this->form; ?>