<div class="page-header">
    <h1>New Presentation
        <small>Enter presentation and survey details here.</small>
    </h1>
</div>
<form class="form-horizontal">
    <fieldset>
        <div class="control-group">
            <label class="control-label" for="location">Location</label>
            <div class="controls">
                <select class="span4">
                    <option>Albany Medical College</option>
                </select>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="type">Presentation Type</label>
            <div class="controls">
                <select class="span2">
                    <option>MED</option>
                </select>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="date">Presentation Date</label>
            <div class="controls">
                <div class="input-append date" id="dp3" data-date="10/05/2012" data-date-format="mm/dd/yyyy">
                    <input class="span2" size="16" type="text" value="10/05/2012" />
                    <span class="add-on"><i class="icon-calendar"></i></span>
                </div>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="textarea">Notes</label>
            <div class="controls">
                <textarea class="span4 input-xlarge" id="textarea" rows="5"></textarea>
            </div>
        </div>
    </fieldset>
    <h2>Survey Results</h2>
    <fieldset class="well">
        <h3>1. In general, I have a basic understanding of ovarian cancer including:</h3>
        <br>
        <div class="control-group form-inline">
            <label class="control-label" for="appendedInputButton">Risk Factors</label>
            <div class="controls">
              <div class="">
                <input class="span2" id="appendedInputButton" size="16" type="text">
                <input class="span2"  size="16" type="text">
              </div>
            </div>
          </div>
          
          <div class="control-group form-inline">
            <label class="control-label" for="appendedInputButton">Signs and symptoms</label>
            <div class="controls">
              <div class="">
                <input class="span2" id="appendedInputButton" size="16" type="text">
                <input class="span2"  size="16" type="text">
              </div>
            </div>
          </div>
          
          <div class="control-group form-inline">
            <label class="control-label" for="appendedInputButton">Diagnostic protocols</label>
            <div class="controls">
              <div class="">
                <input class="span2" id="appendedInputButton" size="16" type="text">
                <input class="span2"  size="16" type="text">
              </div>
            </div>
          </div>
        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Save changes</button>
            <button class="btn">Cancel</button>
        </div>
    </fieldset>
</form>
<div class="alert">
    Right now this page has not been built out...
</div>