<?php
$columns = array('name'=>'Name', 'type'=>'Type','regionName'=>'Region', 'areaName'=>'Area', 'addressCity'=>'City', 'addressState'=>'State');
?>
<table class="table table-striped table-bordered">
	<thead>
		<tr>
		<?php foreach ($columns as $title){
			echo "<th>$title</th>";
			}?>
			<th style="text-align:right;">Actions</th>
		</tr>
	</thead>
	<tbody>
	<?php	foreach ($this->objects as $object) {?>
		<tr>
		<?php foreach ($columns as $get=>$title){
		    $method = 'get' . ucfirst($get);
			echo "<td>{$object->$method()}</td>";
			}?>
			<td style="text-align:right;">
			<!-- 
			<a class="btn btn-small" href="#"><i class="icon-pencil"></i> Edit</a>
			<a class="btn btn-small" href="#"><i class="icon-lock"></i> Reset Password</a>
			<a class="btn btn-small btn-danger" href="#"><i class="icon-trash icon-white"></i></a>
			 -->
			
			</td>
		<?php }?>	
		</tr>
	</tbody>
</table>