<?php
// columns to display in table
$columns = array(
    'name' => 'Name',
    'type' => 'Type',
    'regionName' => 'Region',
    'areaName' => 'Area',
    'addressCity' => 'City',
    'addressState' => 'State'
);
?>
<div class="accordion" id="accordion2">
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
        <em><i class="icon-filter"></i> Filter List...</em>
      </a>
    </div>
    <div id="collapseOne" class="accordion-body collapse">
      <div class="accordion-inner">
        <?php echo $this->form ?>
      </div>
    </div>
  </div>
</div>

<p><a class="btn btn-info" href="/admin/school/excel">Download</a></p>
<table class="table table-striped table-bordered schools">
    <thead>
    <tr>
        <?php foreach ($columns as $title){
            echo "<th>$title</th>";
        }?>
        <th style="text-align:right;">Actions</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->objects as $object): ?>
    <tr>
    <?php foreach ($columns as $get => $title):
        $method = 'get' . ucfirst($get);
        $val = $object->$method();
    ?>
        <td class="<?= $get ?>"><?= $val ?></td>

    <?php endforeach; ?>
        <td class="right">
            <div class="btn-group">
                <a class="btn btn-mini btn-primary" href="/admin/school/edit?id=<?php echo $object->getId() ?>"><i class="icon-edit"></i></a>
                <a class="btn btn-mini" href="/admin/school/view?id=<?php echo $object->getId()?>"><i class="icon-info-sign"></i> Details</a>
            </div>
        </td>
    </tr>
    <?php endforeach ?>
    </tbody>
</table>