<dl class="dl-horizontal<?= $this->school->isInactive() ? ' muted': '' ?>">
    <?php if ($this->school->isInactive()): ?>
    <dt>Inactive</dt>
    <dd>This school is inactive.</dd>
    <?php endif; ?>
  <dt>Program Type:</dt>
  <dd><?php echo $this->school->getType() ? $this->school->getType() : '-'; ?></dd>
  <dt>Region:</dt>
  <dd><?php echo $this->school->getRegionName() ? $this->school->getRegionName(): '-'; ?></dd>
  <dt>Area:</dt>
  <dd><?php echo $this->school->getAreaName() ? $this->school->getAreaName(): '-'; ?></dd>
  <dt>Notes:</dt>
  <dd>
  <?php echo $this->school->getNotes() ? $this->school->getNotes() : '-'; ?>
  </dd>
  <dt>Address:</dt>
  <dd><address>
  <?php echo $this->school->getAddress() ? nl2br($this->school->getAddress()): '-' ?>
</address></dd>
</dl>
<br>
<div class="well">
<div class="btn-toolbar">
    <?php if ($this->can_edit): ?>
    <div class="btn-group">
        <a class="btn btn-primary" href="/admin/school/edit?id=<?php echo $this->school->getId() ?>"><i class="icon-edit"></i> Edit</a>
    </div>
    <?php endif; ?>
    <a class="btn" href="/admin/school">Go Back</a>
</div></div>