<dl class="dl-horizontal">
  <dt>Type:</dt>
  <dd><?php echo $this->school->getType() ? $this->school->getType() : '-'; ?></dd>
  <dt>Region:</dt>
  <dd><?php echo $this->school->getRegionName() ? $this->school->getRegionName(): '-'; ?></dd>
  <dt>Area:</dt>
  <dd><?php echo $this->school->getAreaName() ? $this->school->getAreaName(): '-'; ?></dd>
  <dt>Notes:</dt>
  <dd>
  <?php echo $this->school->getNotes() ? $this->school->getNotes() : '-'; ?>
  </dd>
  <dt>Address:</dt>
  <dd><address>
  <?php echo $this->school->getAddressLineOne() ? $this->school->getAddressLineOne() : '-' ?><br>
    <?php echo $this->school->getAddressLineTwo() ? $this->school->getAddressLineTwo().'<br>' : '' ?>
  <?php echo $this->school->getAddressCity() ? $this->school->getAddressCity().',':''?> <?php echo $this->school->getAddressState() ?> <?php echo $this->school->getAddressZip() ?><br>
</address></dd>
</dl>
<br>
<div class="well">
<div class="btn-toolbar">
  <a class="btn btn-primary" href="/admin/school/edit?id=<?php echo $this->school->getId() ?>"><i class="icon-edit"></i> Edit</a>
  <a class="btn" href="/admin/school">Go Back</a>
</div></div>