<br>
<div class="hero-unit">
<h2>Welcome to the home page of the STS&reg; database system.</h2>
<p>What would you like to do today?</p>
<a class="btn btn-success btn-large" href="/presentation/index/new">
    <i class="icon-file icon-white"></i>
    Enter a New Set of Survey Results
    </a>
<a class="btn btn-large" href="/presentation/index">
    <i class="icon-list-alt"></i>
    View Existing Presentations
    </a>
</div>