<?php
$this->headLink()->appendStylesheet('/js/chosen/chosen.min.css');
$this->headScript()->appendFile('/js/chosen/chosen.jquery.min.js');
$this->headScript()->appendFile('/js/admin/report/presentation.js');
?>
<?php if($this->noData != true): ?>
    <script type='text/javascript' src='https://www.google.com/jsapi'></script>
    <script type='text/javascript'>
     google.load('visualization', '1', {'packages': ['geochart']});
     google.setOnLoadCallback(drawRegionsMap);

      function drawRegionsMap() {
        var data = google.visualization.arrayToDataTable([
            ['State', 'Presentations', 'Students'],
            <?php foreach($this->summary->geo as $state => $info){
                echo "['$state', {$info->presentations}, {$info->participants}],\n";
            }
            ?>
        ]);

        var options = {region: 'US', resolution: 'provinces'};

        var chart = new google.visualization.GeoChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    };
    </script>
<?php endif; ?>
<div class="row">
    <div class="span12">
        <div class="row">
            <div class="span3 well">
                <?php echo $this->form; ?>

                <?php if (!$this->noData == true): ?>
                    <?php echo $this->csv_form; ?>
                <?php endif; ?>
            </div>
            <div class="span8">
                <?php if($this->noData == true): ?>
                <div class="alert alert-info">
                    <h4>Data Unavailable!</h4>
                    There is no information for the choices you selected. Please try again.
                </div>
                <?php else: ?>
                <h3>Data for <?php echo $this->startDate; ?> to <?php echo $this->endDate; ?></h3>
                <div class="row-fluid">
                    <div class="span3 well well-small">
                        <h4><i class="icon-file icon-large"></i>&nbsp;Presentations</h4>
                        <div class="metric metric-large">
                            <strong><?php echo number_format($this->summary->totalPresentations); ?><br /><small>held</small></strong>
                        </div>
                        <br>
                    </div>
                    <div class="span3 well well-small">
                        <h4><i class="icon-user icon-large"></i>&nbsp;Students</h4>
                        <div class="metric metric-large">
                            <strong><?php echo number_format($this->summary->totalStudents); ?><br /><small>reached</small></strong>
                        </div>
                        <br>
                    </div>
                    <div class="span5 well well-small">
                        <h4><i class="icon-beaker icon-large"></i>&nbsp;Medical Schools</h4>

                        <div class="metric">
                            <table>
                                <thead>
                                    <tr>
                                        <th>Type</th>
                                        <th>Presentations</th>
                                        <th>Students</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($this->summary->schools as $type => $values): ?>
                                    <tr>
                                        <td class="row-label"><?= $type ?></td>
                                        <td class="row-int"><?= $values['presentations'] ?></td>
                                        <td class="row-int"><?= $values['participants'] ?></td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>


                </div>
                <h3>Geographic Distribution</h3>
                <div class="row-fluid">
                    <div class="span12">
                        <div id="chart_div"></div>
                    </div>
                </div>

                <div class="row-fluid">
                    <div class="span12">
                        <h4><i class="icon-group icon-large"></i>&nbsp;Presenters</h4>

                        <div class="metric well well-small">
                            <table>
                                <thead>
                                    <tr>
                                        <th>Member</th>
                                        <th>Presentations</th>
                                        <th>Students</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($this->summary->members as $name => $values): ?>
                                    <tr>
                                        <td class="row-label"><?= $name ?></td>
                                        <td class="row-int"><?= $values['presentations'] ?></td>
                                        <td class="row-int"><?= $values['participants'] ?></td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<br>

    
