<?php if(empty($this->objects)): ?>
<div class="alert alert-info">
<h3>
<span>
  <i class="icon-info-sign"></i>
</span>
No presentations yet.</h3>
<p>You have not entered any presentations yet.</p>
</div>
<?php else:
$columns = array('date'=>'Date', 'schoolName'=>'School','schoolAreaCity'=>'City', 'numberOfParticipants'=>'Participants', 'type'=>'Type');
?>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
        <?php foreach ($columns as $title){
            echo "<th>$title</th>";
            }?>
            <th style="text-align:right;">Actions</th>
        </tr>
    </thead>
    <tbody>
    <?php   foreach ($this->objects as $object) {
        ?>
        <tr>
        <?php foreach ($columns as $get=>$title){
            $method = 'get' . ucfirst($get);
            echo "<td>{$object->$method()}</td>";
            }?>
            <td style="text-align:right;">
                <div class="btn-group">
                <a class="btn btn-mini" href="/presentation/index/view?id=<?php echo $object->getId()?>"><i class="icon-info-sign">
                </i> Details</a>
                <a class="btn btn-mini btn-primary" href="/presentation/index/edit?id=<?php echo $object->getId() ?>"><i class="icon-edit"></i></a>
            </div>
            </td>
        <?php }?>
        </tr>
    </tbody>
</table>
<?php endif; ?>
