
<h3>Details</h3>
<dl class="dl-horizontal">
  <dt>Presentation Type:</dt>
  <dd><?php echo $this->presentation->getType() ? $this->presentation->getType() : '-'; ?></dd>

  <dt>School:</dt>
  <dd>
    <?php
    if($this->presentation->getSchoolId()){
      echo '<a href="/admin/school/view?id='. $this->presentation->getSchoolId() .'">'. $this->presentation->getSchoolName(). '</a>';
    } else{
      echo '-';
    }
    ?>
  </dd>
	<?php
	if ($this->presentation->getProfessionalGroupName()):
	?>
	<dt>Professional Group:</dt>
	<dd><?php echo $this->presentation->getProfessionalGroupName(); ?></dd>
	<?php
	endif;
	?>
  <dt>Notes:</dt>
  <dd><?php echo $this->presentation->getNotes() ? $this->presentation->getNotes() : '-'; ?></dd>
  <dt>Members Attending:</dt>
  <?php if($this->presentation->getMembersArray()!=array() ):?>
    <dd>
    <?php foreach($this->presentation->getMembersArray() as $id =>$member):

        switch ($member['status']) {
            case 'Deceased':
                $class = "label label-inverse deceased";
                break;
            case 'Inactive':
                $class = "label";
                break;
            case 'Active':
                $class = "label label-info";
                break;
            default:
                $class = "label label-info";
                break;
        }
        ?>
        <a href="/admin/member/view?id=<?php echo $id ?>"><span class="<?php echo $class?>"><?php echo $member['fullname']; ?></span></a>
    <?php endforeach; ?>
    </dd>
  <?php else: ?>
  -
<?php endif;?>

</dl>
<br>

<h3>Quick Stats</h3>
<div class="row">
  <div class="span7">
    <h4><i class="icon-group"></i> Participants: <?php echo $this->presentation->getNumberOfParticipants() ? $this->presentation->getNumberOfParticipants() : '-'; ?></h4>
  </div>

<div class="span7">
  <h4><i class="icon-signin"></i> Pre Forms Returned: <?php echo $this->presentation->getNumberOfFormsReturnedPre() ? $this->presentation->getNumberOfFormsReturnedPre() : '-'; ?></h4>
  <div class="progress">
    <?php echo (! $this->presentation->getNumberOfFormsReturnedPre()) ? '&nbsp;&nbsp;Data Unavailable!' : ''; ?>
    <div class="bar" style="width: <?php echo $this->presentation->getPreFormsPercentage() ; ?>%;"></div>
  </div>
</div>

<div class="span7">
  <h4><i class="icon-signout"></i> Post Forms Returned: <?php echo $this->presentation->getNumberOfFormsReturnedPost() ? $this->presentation->getNumberOfFormsReturnedPost() : '-'; ?></h4>
  <div class="progress">
    <div class="bar" style="width: <?php echo $this->presentation->getPostFormsPercentage() ; ?>%;"></div>
  </div>
</div>
</div>
<?php if (! is_null($this->survey)): ?>
<h3>Survey Data</h3>
<?php
 function getMultiResponse($question, $choiceId, $ask)
    {
        if ($response = $question->getResponse($choiceId)) {
            return getResponseFromAsk($response, $ask);
        }
        return null;
    }

     function getShortResponse($question, $ask)
    {
        if ($response = $question->getResponse()) {
            return getResponseFromAsk($response, $ask);
        }
        return null;
    }

     function getResponseFromAsk($response, $ask)
    {
        if ($response instanceof STS\Domain\Survey\Response\SingleResponse) {
            return $response->getResponse();
        } else {
            if ($ask === 'pre') {
                return $response->getBeforeResponse();
            } else {
                return $response->getAfterResponse();
            }
        }
    }
        $questionNumber = 1;

        foreach ($this->survey->getQuestions() as $questionId => $question) {
            $prompt = $questionNumber . ". " . $question->getPrompt();
            echo "<p><strong>$prompt</strong></p>";
            echo "<table class=\"table table-hover table-bordered\">";

            if ($question->getType() == 'MultipleChoice' ||$question->getType() == 'TrueFalse') {
              echo "<thead><tr>";
                $whenAsked = $question->whenAsked();
                if ($whenAsked == 1) {
                    $asks = array(
                        'pre'
                    );
                    echo "<th>Choice</th><th>Pre</th>";
                }
                if ($whenAsked == 2) {
                    $asks = array(
                        'post'
                    );
                    echo "<th>Choice</th><th>Post</th>";
                } else {
                    $asks = array(
                        'pre', 'post'
                    );
                    echo "<th>Choice</th><th>Pre</th><th>Post</th>";
                }
              echo "</tr></thead><tbody>";
                foreach ($question->getChoices() as $choiceId => $choice) {
                  echo "<tr><td class=\"span3\">$choice</td>";
                    foreach ($asks as $ask) {
                        echo "<td>";
                        echo getMultiResponse($question, $choiceId, $ask);
                        echo "</td>";
                    }
                    echo "</tr>";
                }
            } elseif ($question->getType() == 'ShortAnswer') {
            echo "<thead><tr>";
                $whenAsked = $question->whenAsked();
                if ($whenAsked == 1) {
                    $asks = array(
                        'pre',
                    );
                    echo "<th>Pre</th>";
                }
                if ($whenAsked == 2) {
                    $asks = array(
                        'post'
                    );
                    echo "<th>Post</th>";
                } else {
                    $asks = array(
                        'pre', 'post'
                    );
                    echo "<th>Pre</th><th>Post</th>";
                }
                echo "<tr>";
                    foreach ($asks as $ask) {
                        echo "<td>";
                        echo getShortResponse($question, $ask);
                        echo "</td>";
                    }
                    echo "</tr>";
              echo "</tr></thead><tbody>";
          }
            $questionNumber++;
            echo"</tbody></table>";
          }
?>
<?php endif; ?>

<div class="well">
<div class="btn-toolbar">
  <a class="btn btn-primary" href="/presentation/index/edit?id=<?php echo $this->presentation->getId() ?>"><i class="icon-edit"></i> Edit</a>
  <a class="btn" href="/presentation">Go Back</a>
</div></div>

