<h3>Details</h3>
<dl class="dl-horizontal">
  <dt>Presentation Type:</dt>
  <dd><?php echo $this->presentation->getType() ? $this->presentation->getType() : '-'; ?></dd>
</dl>
<br>
<h3>Quick Stats</h3>
<div class="row">
  <div class="span7">
    <h4><i class="icon-group"></i> Participants: <?php echo $this->presentation->getNumberOfParticipants() ? $this->presentation->getNumberOfParticipants() : '-'; ?></h4>
  </div>

<div class="span7">
  <h4><i class="icon-signin"></i> Pre Forms Returned: <?php echo $this->presentation->getNumberOfFormsReturnedPre() ? $this->presentation->getNumberOfFormsReturnedPre() : '-'; ?></h4>
  <div class="progress">
    <?php echo (! $this->presentation->getNumberOfFormsReturnedPre()) ? '&nbsp;&nbsp;Data Unavailable!' : ''; ?>
    <div class="bar" style="width: <?php echo $this->presentation->getPreFormsPercentage() ; ?>%;"></div>
  </div>
</div>

<div class="span7">
  <h4><i class="icon-signout"></i> Post Forms Returned: <?php echo $this->presentation->getNumberOfFormsReturnedPost() ? $this->presentation->getNumberOfFormsReturnedPost() : '-'; ?></h4>
  <div class="progress">
    <div class="bar" style="width: <?php echo $this->presentation->getPostFormsPercentage() ; ?>%;"></div>
  </div>
</div>

</div>
<div class="well">
<div class="btn-toolbar">
  <a class="btn" href="/presentation">Go Back</a>
</div></div>