<script type="text/javascript">
	$(document).ready(function() {
		$('.confirm-delete').bind('click', function(){
			var id = $(this).data('id'),
				name = $(this).data('name');
			$('#professionalGroupDeleteModal').data({'id': id, 'name': name}).modal('show');
		})
		$('#professionalGroupDeleteModal').bind('show', function() {
			var id = $(this).data('id'),
				name = $(this).data('name'),
				removeBtn = $(this).find('.btn-danger'),
				href = removeBtn.attr('href');
			content = $('.modal-body p').html();
			$('.confirm-message').html(content.replace(/~professional_group~/, name));
			removeBtn.attr('href', href.replace(/\?id=.*/, '?id=' + id));
		}).modal({
			backdrop: true,
			show: false
		});
	});
</script>
<?php
// columns to display in table
$columns = array(
	'name' => 'Name',
	'regionName' => 'Region',
	'areaName' => 'Area'
);
?>
<div class="accordion" id="accordion2">
	<div class="accordion-group">
		<div class="accordion-heading">
			<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
				<em><i class="icon-filter"></i> Filter List...</em>
			</a>
		</div>
		<div id="collapseOne" class="accordion-body collapse">
			<div class="accordion-inner">
				<?php echo $this->form ?>
			</div>
		</div>
	</div>
</div>

<p><a class="btn btn-info" href="/admin/professionalgroup/excel">Download</a></p>
<table class="table table-striped table-bordered professional_groups">
	<thead>
	<tr>
		<?php foreach ($columns as $title){
			echo "<th>$title</th>";
		}?>
		<th style="text-align:right;">Actions</th>
	</tr>
	</thead>
	<tbody>
	<?php foreach ($this->objects as $object): ?>
		<tr>
			<?php foreach ($columns as $get => $title):
				$method = 'get' . ucfirst($get);
				$val = $object->$method();
				?>
				<td class="<?= $get ?>"><?= $val ?></td>

			<?php endforeach; ?>
			<td class="right">
				<div class="btn-group">
					<?php if ($this->can_edit): ?>
						<a class="btn btn-mini btn-primary" href="/admin/professionalgroup/edit?id=<?php echo $object->getId() ?>"><i class="icon-edit"></i></a>
					<?php endif; ?>
					<?php if ($this->can_view): ?>
						<a class="btn btn-mini" href="/admin/professionalgroup/view?id=<?php echo $object->getId()?>"><i class="icon-info-sign"></i> Details</a>
					<?php endif; ?>
					<?php if ($this->can_delete): ?>
						<a class="btn btn-mini btn-danger confirm-delete" data-name="<?php echo $object->getName(); ?>" data-id="<?php echo $object->getId(); ?>" href="#"><i class="icon-trash"></i></a>
					<?php endif; ?>
				</div>
			</td>
		</tr>
	<?php endforeach ?>
	</tbody>
</table>


<div id="professionalGroupDeleteModal" class="modal hide fade">
	<div class="modal-header">
		<a href="#" class="close">&times;</a>
		<h3>Delete Professional Group</h3>
	</div>
	<div class="modal-body">
		<p class="confirm-message">You are about to delete the professional group
			~professional_group~.
			This procedure is irreversible.</p>
		<p>Are you sure you want to do this?</p>
	</div>
	<div class="modal-footer">
		<a href="/admin/professionalgroup/delete?id=" class="btn btn-danger">Yes</a>
		<a href="javascript:$('#professionalGroupDeleteModal').modal('hide')" class="btn btn-secondary">No</a>
	</div>
</div>