<?php
$n = 1;
foreach ($this->regions as $name => $region):
?>
    <h3><?= $name ?></h3>
    <div class="well">
        <ul class="thumbnails">
            <? foreach ($region['areas'] as $area): ?>
                <li class="span4">
                    <div class="thumbnail sortable-row">
                        <div class="row-fluid">

                            <div class="span6"><?= $area->getCity() ?></div>
                            <?php if ($area->getState()) :?>
                                <div class="span2"><?= $area->getState() ?></div>
                            <?php endif; ?>
                            <div class="btn-group span2">
                                <a class="btn btn-mini btn-primary" href="/admin/area/edit?id=<?= $area->getId() ?>"><i class="icon-edit"></i></a>
                                <a class="btn btn-mini" href="/admin/area/view?id=<?= $area->getId() ?>"><i class="icon-info-sign"></i> Details</a>
                            </div>
                        </div>
                    </div>
                </li>
            <? endforeach; ?>
        </ul>
    </div>
<? endforeach; ?>
