<!doctype html>
<html lang="en">
    <head>
    	<meta charset="utf-8">
        <?php echo $this->headTitle() ?>
        <meta name="description" content="">
    	<meta name="author" content="">
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->headScript() ?>
	</head>
  	<body>
  		<h1>Sample Layout</h1>
        <?php echo $this->layout()->content;?>
    </body>
</html>