<div class="navbar">
	<div class="navbar-inner">
		<div class="container" style="width: auto;">

			<!-- .btn-navbar is used as the toggle for collapsed navbar content -->
			<a class="btn btn-navbar" data-toggle="collapse"
				data-target=".nav-collapse"> <span class="icon-bar"></span> <span
				class="icon-bar"></span> <span class="icon-bar"></span>
			</a>

			<!-- Be sure to leave the brand out there if you want it shown -->
			<a class="brand" href="#">Survivors Teaching Students</a>

			<!-- Everything you want hidden at 940px or less, place within here -->
			<div class="nav-collapse">
				<!-- .nav, .navbar-search, .navbar-form, etc -->

				<ul class="nav pull-right">
        <?php //echo $this->nav?>
        <?php if($this->authenticated):?>
        <li class="divider-vertical"></li>
					<li class="dropdown"><a href="#" class="dropdown-toggle"
						data-toggle="dropdown"><i class="icon-user icon-white"></i> <?php echo $this->userName ?> <b
							class="caret"></b> </a>
						<ul class="dropdown-menu">
							<!--<li><a href="/main/profile">Profile</a></li>
							<li class="divider"></li>-->
							<li><a href="/session/logout">Logout</a></li>
						</ul></li>
						<?php endif;?>
				</ul>
			</div>

		</div>
	</div>
</div>
